-- Phase 8: Actual financials are sourced only from sales and expenses.
CREATE TABLE public.expense_categories (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid REFERENCES public.farms(id) ON DELETE CASCADE, name text NOT NULL CHECK(char_length(trim(name))>0), is_system boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(farm_id,name)
);
INSERT INTO public.expense_categories(farm_id,name,is_system) VALUES (NULL,'Feed',true),(NULL,'Medicine',true),(NULL,'Vaccine',true),(NULL,'Labour',true),(NULL,'Electricity',true),(NULL,'Transport',true),(NULL,'Maintenance',true),(NULL,'Packaging',true),(NULL,'Salary',true),(NULL,'Miscellaneous',true) ON CONFLICT(farm_id,name) DO NOTHING;
CREATE TABLE public.expenses (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, flock_id uuid REFERENCES public.flocks(id) ON DELETE RESTRICT, expense_date date NOT NULL, category_id uuid NOT NULL REFERENCES public.expense_categories(id) ON DELETE RESTRICT, amount numeric(14,2) NOT NULL CHECK(amount>0), vendor text NOT NULL DEFAULT '', payment_method text NOT NULL DEFAULT '', reference text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', attachment_path text NOT NULL DEFAULT '', entered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE TABLE public.financial_transactions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, flock_id uuid REFERENCES public.flocks(id) ON DELETE RESTRICT, transaction_date date NOT NULL, transaction_type text NOT NULL CHECK(transaction_type IN ('REVENUE','EXPENSE')), source_type text NOT NULL CHECK(source_type IN ('DISPATCH','EXPENSE')), dispatch_id uuid UNIQUE REFERENCES public.dispatches(id) ON DELETE RESTRICT, expense_id uuid UNIQUE REFERENCES public.expenses(id) ON DELETE RESTRICT, category_id uuid REFERENCES public.expense_categories(id) ON DELETE RESTRICT, amount numeric(14,2) NOT NULL CHECK(amount>=0), description text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), CHECK((source_type='DISPATCH' AND transaction_type='REVENUE' AND dispatch_id IS NOT NULL AND expense_id IS NULL) OR (source_type='EXPENSE' AND transaction_type='EXPENSE' AND expense_id IS NOT NULL AND dispatch_id IS NULL))
);
CREATE TABLE public.daily_financial_summary (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, flock_id uuid REFERENCES public.flocks(id) ON DELETE RESTRICT, flock_scope_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000', summary_date date NOT NULL, revenue numeric(14,2) NOT NULL DEFAULT 0, feed_cost numeric(14,2) NOT NULL DEFAULT 0, medicine_cost numeric(14,2) NOT NULL DEFAULT 0, labour_cost numeric(14,2) NOT NULL DEFAULT 0, transport_cost numeric(14,2) NOT NULL DEFAULT 0, other_expenses numeric(14,2) NOT NULL DEFAULT 0, gross_profit numeric(14,2) NOT NULL DEFAULT 0, net_profit numeric(14,2) NOT NULL DEFAULT 0, eggs integer NOT NULL DEFAULT 0, trays numeric(12,3) NOT NULL DEFAULT 0, average_live_birds numeric(12,3) NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(farm_id,flock_scope_id,summary_date)
);
-- Planning data is isolated; actual P&L reads neither this table nor simulation entries.
CREATE TABLE public.financial_plan_entries (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, flock_id uuid REFERENCES public.flocks(id) ON DELETE CASCADE, plan_type text NOT NULL CHECK(plan_type IN ('BUDGET','FORECAST','SIMULATION')), entry_date date NOT NULL, category text NOT NULL, amount numeric(14,2) NOT NULL, notes text NOT NULL DEFAULT '', entered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE INDEX expenses_farm_date_idx ON public.expenses(farm_id,expense_date DESC); CREATE INDEX financial_transactions_farm_date_idx ON public.financial_transactions(farm_id,transaction_date DESC); CREATE INDEX daily_financial_summary_farm_date_idx ON public.daily_financial_summary(farm_id,summary_date DESC); CREATE INDEX financial_plan_entries_farm_type_idx ON public.financial_plan_entries(farm_id,plan_type,entry_date);
CREATE OR REPLACE FUNCTION public.sync_dispatch_financial_transaction() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE amount_value numeric; BEGIN SELECT debit INTO amount_value FROM public.buyer_ledger WHERE dispatch_id=NEW.id; IF amount_value IS NULL THEN RETURN NEW; END IF; INSERT INTO public.financial_transactions(farm_id,flock_id,transaction_date,transaction_type,source_type,dispatch_id,amount,description) VALUES(NEW.farm_id,NEW.flock_id,NEW.dispatch_date,'REVENUE','DISPATCH',NEW.id,amount_value,NEW.invoice_reference) ON CONFLICT(dispatch_id) DO UPDATE SET amount=EXCLUDED.amount,transaction_date=EXCLUDED.transaction_date,flock_id=EXCLUDED.flock_id,description=EXCLUDED.description; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.sync_expense_financial_transaction() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.financial_transactions(farm_id,flock_id,transaction_date,transaction_type,source_type,expense_id,category_id,amount,description) VALUES(NEW.farm_id,NEW.flock_id,NEW.expense_date,'EXPENSE','EXPENSE',NEW.id,NEW.category_id,NEW.amount,NEW.notes) ON CONFLICT(expense_id) DO UPDATE SET amount=EXCLUDED.amount,transaction_date=EXCLUDED.transaction_date,category_id=EXCLUDED.category_id,description=EXCLUDED.description,flock_id=EXCLUDED.flock_id; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.sync_sale_ledger_financial_transaction() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE d public.dispatches; BEGIN IF NEW.entry_type<>'SALE' OR NEW.dispatch_id IS NULL THEN RETURN NEW; END IF; SELECT * INTO d FROM public.dispatches WHERE id=NEW.dispatch_id; INSERT INTO public.financial_transactions(farm_id,flock_id,transaction_date,transaction_type,source_type,dispatch_id,amount,description) VALUES(d.farm_id,d.flock_id,d.dispatch_date,'REVENUE','DISPATCH',d.id,NEW.debit,d.invoice_reference) ON CONFLICT(dispatch_id) DO UPDATE SET amount=EXCLUDED.amount,transaction_date=EXCLUDED.transaction_date,flock_id=EXCLUDED.flock_id,description=EXCLUDED.description; RETURN NEW; END $$;
CREATE TRIGGER dispatch_financial_transaction AFTER INSERT OR UPDATE ON public.dispatches FOR EACH ROW EXECUTE FUNCTION public.sync_dispatch_financial_transaction(); CREATE TRIGGER sale_ledger_financial_transaction AFTER INSERT OR UPDATE ON public.buyer_ledger FOR EACH ROW EXECUTE FUNCTION public.sync_sale_ledger_financial_transaction(); CREATE TRIGGER expense_financial_transaction AFTER INSERT OR UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION public.sync_expense_financial_transaction();
CREATE OR REPLACE FUNCTION public.refresh_daily_financial_summary(p_farm_id uuid,p_date date,p_flock_id uuid DEFAULT NULL) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE feed numeric; medicine numeric; labour numeric; transport numeric; other numeric; rev numeric; eggs_value integer; trays_value numeric; birds numeric; BEGIN SELECT COALESCE(sum(amount) FILTER(WHERE transaction_type='REVENUE'),0) INTO rev FROM financial_transactions WHERE farm_id=p_farm_id AND transaction_date=p_date AND (p_flock_id IS NULL OR flock_id=p_flock_id); SELECT COALESCE(sum(e.amount) FILTER(WHERE c.name='Feed'),0),COALESCE(sum(e.amount) FILTER(WHERE c.name='Medicine'),0),COALESCE(sum(e.amount) FILTER(WHERE c.name IN('Labour','Salary')),0),COALESCE(sum(e.amount) FILTER(WHERE c.name='Transport'),0),COALESCE(sum(e.amount) FILTER(WHERE c.name NOT IN('Feed','Medicine','Labour','Salary','Transport')),0) INTO feed,medicine,labour,transport,other FROM expenses e JOIN expense_categories c ON c.id=e.category_id WHERE e.farm_id=p_farm_id AND e.expense_date=p_date AND (p_flock_id IS NULL OR e.flock_id=p_flock_id); SELECT COALESCE(sum(i.eggs),0),COALESCE(sum(i.trays),0) INTO eggs_value,trays_value FROM dispatches d JOIN dispatch_items i ON i.dispatch_id=d.id WHERE d.farm_id=p_farm_id AND d.dispatch_date=p_date AND (p_flock_id IS NULL OR d.flock_id=p_flock_id); SELECT COALESCE(avg((opening_live_birds+closing_live_birds)/2.0),0) INTO birds FROM production_daily WHERE farm_id=p_farm_id AND date=p_date AND (p_flock_id IS NULL OR flock_id=p_flock_id); INSERT INTO daily_financial_summary(farm_id,flock_id,flock_scope_id,summary_date,revenue,feed_cost,medicine_cost,labour_cost,transport_cost,other_expenses,gross_profit,net_profit,eggs,trays,average_live_birds) VALUES(p_farm_id,p_flock_id,COALESCE(p_flock_id,'00000000-0000-0000-0000-000000000000'),p_date,rev,feed,medicine,labour,transport,other,rev-feed-medicine-labour-transport-other,rev-feed-medicine-labour-transport-other,eggs_value,trays_value,birds) ON CONFLICT(farm_id,flock_scope_id,summary_date) DO UPDATE SET revenue=EXCLUDED.revenue,feed_cost=EXCLUDED.feed_cost,medicine_cost=EXCLUDED.medicine_cost,labour_cost=EXCLUDED.labour_cost,transport_cost=EXCLUDED.transport_cost,other_expenses=EXCLUDED.other_expenses,gross_profit=EXCLUDED.gross_profit,net_profit=EXCLUDED.net_profit,eggs=EXCLUDED.eggs,trays=EXCLUDED.trays,average_live_birds=EXCLUDED.average_live_birds,updated_at=timezone('utc',now()); END $$;
CREATE OR REPLACE VIEW public.weekly_financial_summary WITH(security_invoker=true) AS SELECT farm_id,flock_id,date_trunc('week',summary_date)::date AS period_start,sum(revenue) revenue,sum(feed_cost) feed_cost,sum(medicine_cost) medicine_cost,sum(labour_cost) labour_cost,sum(transport_cost) transport_cost,sum(other_expenses) other_expenses,sum(gross_profit) gross_profit,sum(net_profit) net_profit,sum(eggs) eggs,sum(trays) trays FROM daily_financial_summary GROUP BY farm_id,flock_id,date_trunc('week',summary_date);
CREATE OR REPLACE VIEW public.monthly_financial_summary WITH(security_invoker=true) AS SELECT farm_id,flock_id,date_trunc('month',summary_date)::date AS period_start,sum(revenue) revenue,sum(feed_cost) feed_cost,sum(medicine_cost) medicine_cost,sum(labour_cost) labour_cost,sum(transport_cost) transport_cost,sum(other_expenses) other_expenses,sum(gross_profit) gross_profit,sum(net_profit) net_profit,sum(eggs) eggs,sum(trays) trays FROM daily_financial_summary GROUP BY farm_id,flock_id,date_trunc('month',summary_date);
CREATE OR REPLACE VIEW public.farm_profitability WITH(security_invoker=true) AS SELECT farm_id,sum(revenue) revenue,sum(net_profit) net_profit,sum(eggs) eggs,sum(trays) trays,CASE WHEN sum(eggs)>0 THEN sum(net_profit)/sum(eggs) END AS profit_per_egg,CASE WHEN sum(trays)>0 THEN sum(net_profit)/sum(trays) END AS profit_per_tray FROM daily_financial_summary WHERE flock_id IS NULL GROUP BY farm_id;
CREATE OR REPLACE VIEW public.flock_profitability WITH(security_invoker=true) AS SELECT farm_id,flock_id,sum(revenue) revenue,sum(net_profit) net_profit,sum(eggs) eggs,sum(trays) trays,CASE WHEN sum(average_live_birds)>0 THEN sum(net_profit)/sum(average_live_birds) END AS profit_per_bird,CASE WHEN sum(eggs)>0 THEN sum(net_profit)/sum(eggs) END AS profit_per_egg,CASE WHEN sum(trays)>0 THEN sum(net_profit)/sum(trays) END AS profit_per_tray FROM daily_financial_summary WHERE flock_id IS NOT NULL GROUP BY farm_id,flock_id;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY; ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.daily_financial_summary ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_plan_entries ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.expense_categories,public.financial_transactions,public.daily_financial_summary,public.weekly_financial_summary,public.monthly_financial_summary,public.farm_profitability,public.flock_profitability TO authenticated; GRANT SELECT,INSERT,UPDATE,DELETE ON public.expenses,public.financial_plan_entries TO authenticated; GRANT INSERT,UPDATE,DELETE ON public.expense_categories TO authenticated;
CREATE POLICY expense_categories_select ON public.expense_categories FOR SELECT TO authenticated USING(farm_id IS NULL OR public.is_farm_member(farm_id)); CREATE POLICY expense_categories_write ON public.expense_categories FOR ALL TO authenticated USING(farm_id IS NOT NULL AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(farm_id IS NOT NULL AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY expenses_members ON public.expenses FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY expenses_write ON public.expenses FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(entered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])); CREATE POLICY transactions_members ON public.financial_transactions FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY summaries_members ON public.daily_financial_summary FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY plans_members ON public.financial_plan_entries FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY plans_write ON public.financial_plan_entries FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(entered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
