-- Phase 10: compact, RLS-respecting aggregates for the management dashboard.
CREATE OR REPLACE VIEW public.dashboard_production_daily WITH(security_invoker=true) AS
SELECT d.farm_id,d.shed_id,d.flock_id,d.date, sum(d.opening_live_birds) opening_live_birds,sum(d.closing_live_birds) live_birds,sum(d.mortality) mortality,sum(d.feed_consumed_kg) feed_used_kg,sum(d.eggs_collected) eggs_collected,CASE WHEN sum((d.opening_live_birds+d.closing_live_birds)/2.0)>0 THEN sum(d.eggs_collected)/sum((d.opening_live_birds+d.closing_live_birds)/2.0)*100 END hen_day_percent FROM public.production_daily d GROUP BY d.farm_id,d.shed_id,d.flock_id,d.date;
CREATE OR REPLACE VIEW public.dashboard_grade_daily WITH(security_invoker=true) AS
SELECT d.farm_id,d.shed_id,d.flock_id,d.date,g.code grade,sum(e.quantity) eggs FROM public.production_daily d JOIN public.production_daily_egg_grade_entries e ON e.production_daily_id=d.id JOIN public.production_egg_grades g ON g.id=e.egg_grade_id GROUP BY d.farm_id,d.shed_id,d.flock_id,d.date,g.code;
CREATE OR REPLACE VIEW public.dashboard_sales_daily WITH(security_invoker=true) AS
SELECT x.farm_id,x.flock_id,x.dispatch_date date,sum(i.eggs) eggs,sum(i.trays) trays,sum(i.amount) revenue,CASE WHEN sum(i.trays)>0 THEN sum(i.amount)/sum(i.trays) END egg_rate FROM public.dispatches x JOIN public.dispatch_items i ON i.dispatch_id=x.id GROUP BY x.farm_id,x.flock_id,x.dispatch_date;
CREATE OR REPLACE VIEW public.dashboard_finance_daily WITH(security_invoker=true) AS
SELECT farm_id,flock_id,transaction_date date,sum(amount) FILTER(WHERE transaction_type='REVENUE') revenue,sum(amount) FILTER(WHERE transaction_type='EXPENSE') expenses,sum(amount) FILTER(WHERE transaction_type='REVENUE')-sum(amount) FILTER(WHERE transaction_type='EXPENSE') profit FROM public.financial_transactions GROUP BY farm_id,flock_id,transaction_date;
CREATE OR REPLACE VIEW public.dashboard_feed_stock WITH(security_invoker=true) AS
SELECT s.farm_id,sum(s.quantity_kg) stock_kg,CASE WHEN sum(COALESCE(c.used_kg,0))>0 THEN sum(s.quantity_kg)/sum(c.used_kg) END stock_days FROM (SELECT fi.farm_id,fi.id,fi.opening_quantity_kg+COALESCE((SELECT sum(quantity_kg) FROM feed_purchases p WHERE p.feed_item_id=fi.id),0)+COALESCE((SELECT sum(quantity_kg) FROM feed_adjustments a WHERE a.feed_item_id=fi.id),0)-COALESCE((SELECT sum(quantity_kg) FROM feed_consumption u WHERE u.feed_item_id=fi.id),0) quantity_kg FROM feed_items fi) s LEFT JOIN (SELECT feed_item_id,sum(quantity_kg)/NULLIF(count(DISTINCT consumed_date),0) used_kg FROM feed_consumption WHERE consumed_date>=CURRENT_DATE-7 GROUP BY feed_item_id) c ON c.feed_item_id=s.id GROUP BY s.farm_id;
CREATE OR REPLACE VIEW public.dashboard_critical_alerts WITH(security_invoker=true) AS
SELECT farm_id,'MEDICINE_EXPIRY' alert_type,name||' batch '||batch||' expires '||expiry_date::text message,expiry_date due_date FROM medicine_expiry_alerts UNION ALL SELECT farm_id,'VACCINATION_DUE',vaccine_name||' due '||planned_date::text,planned_date FROM upcoming_vaccination_reminders UNION ALL SELECT farm_id,'FEED_STOCK', 'Feed stock below three days',CURRENT_DATE FROM dashboard_feed_stock WHERE stock_days IS NOT NULL AND stock_days<3;
GRANT SELECT ON public.dashboard_production_daily,public.dashboard_grade_daily,public.dashboard_sales_daily,public.dashboard_finance_daily,public.dashboard_feed_stock,public.dashboard_critical_alerts TO authenticated;
