-- Phase 7: commercial transactions. Buyer balances are ledger-derived, never writable balances.
CREATE TABLE public.buyers (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, name text NOT NULL CHECK(char_length(trim(name))>0), code text NOT NULL CHECK(char_length(trim(code))>0), phone text NOT NULL DEFAULT '', address text NOT NULL DEFAULT '', location text NOT NULL DEFAULT '', payment_terms text NOT NULL DEFAULT '', credit_limit numeric(14,2) NOT NULL DEFAULT 0 CHECK(credit_limit>=0), opening_balance numeric(14,2) NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(farm_id,code)
);
CREATE TABLE public.dispatches (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, buyer_id uuid NOT NULL REFERENCES public.buyers(id) ON DELETE RESTRICT, flock_id uuid REFERENCES public.flocks(id) ON DELETE RESTRICT, dispatch_date date NOT NULL, transport numeric(14,2) NOT NULL DEFAULT 0 CHECK(transport>=0), loading_charges numeric(14,2) NOT NULL DEFAULT 0 CHECK(loading_charges>=0), other_charges numeric(14,2) NOT NULL DEFAULT 0 CHECK(other_charges>=0), invoice_reference text NOT NULL DEFAULT '', vehicle text NOT NULL DEFAULT '', driver text NOT NULL DEFAULT '', remarks text NOT NULL DEFAULT '', allow_oversell boolean NOT NULL DEFAULT false, entered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE TABLE public.dispatch_items (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dispatch_id uuid NOT NULL REFERENCES public.dispatches(id) ON DELETE CASCADE, egg_grade_id uuid NOT NULL REFERENCES public.production_egg_grades(id) ON DELETE RESTRICT, trays numeric(12,3) NOT NULL CHECK(trays>0), eggs integer NOT NULL CHECK(eggs>0), rate numeric(14,4) NOT NULL CHECK(rate>=0), amount numeric(14,2) GENERATED ALWAYS AS (round((trays * rate)::numeric,2)) STORED, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(dispatch_id,egg_grade_id)
);
CREATE TABLE public.buyer_ledger (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, buyer_id uuid NOT NULL REFERENCES public.buyers(id) ON DELETE RESTRICT, entry_date date NOT NULL, entry_type text NOT NULL CHECK(entry_type IN ('OPENING','SALE','PAYMENT')), debit numeric(14,2) NOT NULL DEFAULT 0 CHECK(debit>=0), credit numeric(14,2) NOT NULL DEFAULT 0 CHECK(credit>=0), dispatch_id uuid UNIQUE REFERENCES public.dispatches(id) ON DELETE RESTRICT, payment_id uuid UNIQUE, reference text NOT NULL DEFAULT '', remarks text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), CHECK((debit=0) <> (credit=0))
);
CREATE TABLE public.buyer_payments (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, buyer_id uuid NOT NULL REFERENCES public.buyers(id) ON DELETE RESTRICT, payment_date date NOT NULL, amount numeric(14,2) NOT NULL CHECK(amount>0), reference text NOT NULL DEFAULT '', method text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', entered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
ALTER TABLE public.buyer_ledger ADD CONSTRAINT buyer_ledger_payment_fk FOREIGN KEY(payment_id) REFERENCES public.buyer_payments(id) ON DELETE RESTRICT;
CREATE INDEX dispatches_buyer_date_idx ON public.dispatches(buyer_id,dispatch_date DESC); CREATE INDEX dispatch_items_grade_idx ON public.dispatch_items(egg_grade_id); CREATE INDEX buyer_ledger_buyer_date_idx ON public.buyer_ledger(buyer_id,entry_date); CREATE INDEX buyer_payments_buyer_date_idx ON public.buyer_payments(buyer_id,payment_date DESC);
CREATE OR REPLACE FUNCTION public.available_saleable_eggs(p_farm uuid,p_flock uuid,p_grade uuid) RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT COALESCE((SELECT sum(CASE WHEN g.code='BROKEN' THEN 0 WHEN g.code='REJECT' THEN 0 ELSE e.quantity END) FROM production_daily_egg_grade_entries e JOIN production_daily d ON d.id=e.production_daily_id JOIN production_egg_grades g ON g.id=e.egg_grade_id WHERE d.farm_id=p_farm AND (p_flock IS NULL OR d.flock_id=p_flock) AND e.egg_grade_id=p_grade),0)-COALESCE((SELECT sum(i.eggs) FROM dispatch_items i JOIN dispatches x ON x.id=i.dispatch_id WHERE x.farm_id=p_farm AND (p_flock IS NULL OR x.flock_id=p_flock) AND i.egg_grade_id=p_grade),0) $$;
CREATE OR REPLACE FUNCTION public.assert_dispatch_item_available() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE h public.dispatches; available bigint; BEGIN SELECT * INTO h FROM public.dispatches WHERE id=NEW.dispatch_id; SELECT public.available_saleable_eggs(h.farm_id,h.flock_id,NEW.egg_grade_id) INTO available; IF NEW.eggs>available AND NOT h.allow_oversell THEN RAISE EXCEPTION 'Dispatch exceeds available saleable eggs'; END IF; IF NEW.eggs>available AND h.allow_oversell AND NOT public.user_has_farm_role(h.farm_id,ARRAY['OWNER']::public.farm_role[]) THEN RAISE EXCEPTION 'Only an owner may authorize an oversell'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.sync_dispatch_ledger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE h public.dispatches; total numeric; dispatch_uuid uuid; BEGIN dispatch_uuid:=CASE WHEN TG_TABLE_NAME='dispatches' THEN COALESCE(NEW.id,OLD.id) ELSE COALESCE(NEW.dispatch_id,OLD.dispatch_id) END; SELECT * INTO h FROM public.dispatches WHERE id=dispatch_uuid; SELECT COALESCE(sum(amount),0)+h.transport+h.loading_charges+h.other_charges INTO total FROM public.dispatch_items WHERE dispatch_id=h.id; IF total=0 THEN DELETE FROM public.buyer_ledger WHERE dispatch_id=h.id; ELSE INSERT INTO public.buyer_ledger(farm_id,buyer_id,entry_date,entry_type,debit,dispatch_id,reference,remarks) VALUES(h.farm_id,h.buyer_id,h.dispatch_date,'SALE',total,h.id,h.invoice_reference,h.remarks) ON CONFLICT(dispatch_id) DO UPDATE SET debit=EXCLUDED.debit,entry_date=EXCLUDED.entry_date,reference=EXCLUDED.reference,remarks=EXCLUDED.remarks; END IF; IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF; END $$;
CREATE OR REPLACE FUNCTION public.create_buyer_opening_ledger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NEW.opening_balance<>0 THEN INSERT INTO public.buyer_ledger(farm_id,buyer_id,entry_date,entry_type,debit,credit,reference) VALUES(NEW.farm_id,NEW.id,CURRENT_DATE,'OPENING',GREATEST(NEW.opening_balance,0),GREATEST(-NEW.opening_balance,0),'Opening balance'); END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.create_payment_ledger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.buyer_ledger(farm_id,buyer_id,entry_date,entry_type,credit,payment_id,reference,remarks) VALUES(NEW.farm_id,NEW.buyer_id,NEW.payment_date,'PAYMENT',NEW.amount,NEW.id,NEW.reference,NEW.notes); RETURN NEW; END $$;
CREATE TRIGGER dispatch_item_availability BEFORE INSERT OR UPDATE ON public.dispatch_items FOR EACH ROW EXECUTE FUNCTION public.assert_dispatch_item_available(); CREATE TRIGGER dispatch_item_ledger AFTER INSERT OR UPDATE OR DELETE ON public.dispatch_items FOR EACH ROW EXECUTE FUNCTION public.sync_dispatch_ledger(); CREATE TRIGGER dispatch_header_ledger AFTER UPDATE ON public.dispatches FOR EACH ROW EXECUTE FUNCTION public.sync_dispatch_ledger(); CREATE TRIGGER buyer_opening_ledger AFTER INSERT ON public.buyers FOR EACH ROW EXECUTE FUNCTION public.create_buyer_opening_ledger(); CREATE TRIGGER payment_ledger AFTER INSERT ON public.buyer_payments FOR EACH ROW EXECUTE FUNCTION public.create_payment_ledger();
CREATE OR REPLACE VIEW public.buyer_balances WITH(security_invoker=true) AS SELECT b.id AS buyer_id,b.farm_id,b.name,COALESCE(sum(l.debit-l.credit),0) AS closing_balance FROM buyers b LEFT JOIN buyer_ledger l ON l.buyer_id=b.id GROUP BY b.id,b.farm_id,b.name;
CREATE OR REPLACE VIEW public.buyer_outstanding_aging WITH(security_invoker=true) AS SELECT buyer_id,farm_id,COALESCE(sum(CASE WHEN entry_date>=CURRENT_DATE-7 THEN debit-credit ELSE 0 END),0) AS current,COALESCE(sum(CASE WHEN entry_date BETWEEN CURRENT_DATE-7 AND CURRENT_DATE-1 THEN debit-credit ELSE 0 END),0) AS days_1_7,COALESCE(sum(CASE WHEN entry_date BETWEEN CURRENT_DATE-30 AND CURRENT_DATE-8 THEN debit-credit ELSE 0 END),0) AS days_8_30,COALESCE(sum(CASE WHEN entry_date BETWEEN CURRENT_DATE-60 AND CURRENT_DATE-31 THEN debit-credit ELSE 0 END),0) AS days_31_60,COALESCE(sum(CASE WHEN entry_date<CURRENT_DATE-60 THEN debit-credit ELSE 0 END),0) AS days_60_plus FROM buyer_ledger GROUP BY buyer_id,farm_id;
ALTER TABLE public.buyers ENABLE ROW LEVEL SECURITY; ALTER TABLE public.dispatches ENABLE ROW LEVEL SECURITY; ALTER TABLE public.dispatch_items ENABLE ROW LEVEL SECURITY; ALTER TABLE public.buyer_ledger ENABLE ROW LEVEL SECURITY; ALTER TABLE public.buyer_payments ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.buyers,public.dispatches,public.dispatch_items,public.buyer_payments TO authenticated; GRANT SELECT ON public.buyer_ledger,public.buyer_balances,public.buyer_outstanding_aging TO authenticated;
CREATE POLICY buyers_members ON public.buyers FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY buyers_write ON public.buyers FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY dispatches_members ON public.dispatches FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY dispatches_write ON public.dispatches FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(entered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY dispatch_items_members ON public.dispatch_items FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM dispatches d WHERE d.id=dispatch_id AND public.is_farm_member(d.farm_id))); CREATE POLICY dispatch_items_write ON public.dispatch_items FOR ALL TO authenticated USING(EXISTS(SELECT 1 FROM dispatches d WHERE d.id=dispatch_id AND public.user_has_farm_role(d.farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]))) WITH CHECK(EXISTS(SELECT 1 FROM dispatches d WHERE d.id=dispatch_id AND public.user_has_farm_role(d.farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])));
CREATE POLICY buyer_ledger_members ON public.buyer_ledger FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY buyer_payments_members ON public.buyer_payments FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY buyer_payments_write ON public.buyer_payments FOR ALL TO authenticated USING( public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(entered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
