-- Phase 6: medicine lots and vaccinations. Schedules are data, never application constants.
CREATE TABLE public.medicines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT,
 name text NOT NULL CHECK(char_length(trim(name)) > 0), manufacturer text NOT NULL DEFAULT '', category text NOT NULL DEFAULT '', unit text NOT NULL CHECK(char_length(trim(unit)) > 0),
 opening_stock numeric(12,3) NOT NULL DEFAULT 0 CHECK(opening_stock >= 0), opening_cost numeric(12,4), notes text NOT NULL DEFAULT '', is_active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(farm_id,name)
);
CREATE TABLE public.medicine_purchases (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), medicine_id uuid NOT NULL REFERENCES public.medicines(id) ON DELETE RESTRICT, farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT,
 supplier text NOT NULL DEFAULT '', quantity numeric(12,3) NOT NULL CHECK(quantity > 0), unit text NOT NULL, purchase_cost numeric(12,4) NOT NULL CHECK(purchase_cost >= 0), batch text NOT NULL DEFAULT '', purchase_date date NOT NULL, expiry_date date, notes text NOT NULL DEFAULT '', entered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), CHECK(expiry_date IS NULL OR expiry_date >= purchase_date)
);
CREATE TABLE public.medicine_usage (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), medicine_id uuid NOT NULL REFERENCES public.medicines(id) ON DELETE RESTRICT, farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT,
 shed_id uuid, flock_id uuid, usage_date date NOT NULL, quantity numeric(12,3) NOT NULL CHECK(quantity > 0), reason text NOT NULL CHECK(char_length(trim(reason)) > 0), administered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
 FOREIGN KEY(shed_id,farm_id) REFERENCES public.sheds(id,farm_id) ON DELETE RESTRICT, FOREIGN KEY(flock_id,farm_id) REFERENCES public.flocks(id,farm_id) ON DELETE RESTRICT
);
CREATE TABLE public.vaccines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, name text NOT NULL CHECK(char_length(trim(name)) > 0), manufacturer text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()), UNIQUE(farm_id,name)
);
CREATE TABLE public.vaccination_schedules (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, vaccine_id uuid NOT NULL REFERENCES public.vaccines(id) ON DELETE RESTRICT, target_flock_id uuid REFERENCES public.flocks(id) ON DELETE CASCADE, planned_date date NOT NULL, dose text NOT NULL DEFAULT '', route text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '', is_active boolean NOT NULL DEFAULT true, created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE TABLE public.vaccination_records (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schedule_id uuid REFERENCES public.vaccination_schedules(id) ON DELETE SET NULL, vaccine_id uuid NOT NULL REFERENCES public.vaccines(id) ON DELETE RESTRICT, farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE RESTRICT, target_flock_id uuid REFERENCES public.flocks(id) ON DELETE RESTRICT, planned_date date, actual_date date NOT NULL, dose text NOT NULL DEFAULT '', route text NOT NULL DEFAULT '', administered_by uuid NOT NULL DEFAULT auth.uid() REFERENCES public.profiles(id), notes text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT timezone('utc',now()), updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE INDEX medicine_purchases_expiry_idx ON public.medicine_purchases(farm_id,expiry_date); CREATE INDEX medicine_usage_flock_date_idx ON public.medicine_usage(flock_id,usage_date DESC); CREATE INDEX vaccination_schedules_due_idx ON public.vaccination_schedules(farm_id,planned_date) WHERE is_active; CREATE INDEX vaccination_records_flock_date_idx ON public.vaccination_records(target_flock_id,actual_date DESC);
CREATE OR REPLACE VIEW public.medicine_stock WITH (security_invoker=true) AS SELECT m.id AS medicine_id,m.farm_id,m.name,m.unit,m.opening_stock + COALESCE((SELECT sum(quantity) FROM public.medicine_purchases p WHERE p.medicine_id=m.id),0)-COALESCE((SELECT sum(quantity) FROM public.medicine_usage u WHERE u.medicine_id=m.id),0) AS stock FROM public.medicines m;
CREATE OR REPLACE VIEW public.upcoming_vaccination_reminders WITH (security_invoker=true) AS SELECT s.id AS schedule_id,s.farm_id,s.target_flock_id,s.planned_date,v.name AS vaccine_name,s.dose,s.route FROM public.vaccination_schedules s JOIN public.vaccines v ON v.id=s.vaccine_id WHERE s.is_active AND s.planned_date >= CURRENT_DATE AND s.planned_date <= CURRENT_DATE + 14 AND NOT EXISTS(SELECT 1 FROM public.vaccination_records r WHERE r.schedule_id=s.id);
CREATE OR REPLACE VIEW public.medicine_expiry_alerts WITH (security_invoker=true) AS SELECT p.id AS purchase_id,p.farm_id,p.medicine_id,m.name,p.batch,p.expiry_date,p.quantity,p.unit FROM public.medicine_purchases p JOIN public.medicines m ON m.id=p.medicine_id WHERE p.expiry_date IS NOT NULL AND p.expiry_date <= CURRENT_DATE + 30;
CREATE OR REPLACE FUNCTION public.assert_medicine_usage_stock() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF (SELECT stock FROM public.medicine_stock WHERE medicine_id=NEW.medicine_id) < 0 THEN RAISE EXCEPTION 'Medicine stock cannot be negative'; END IF; RETURN NEW; END $$;
CREATE TRIGGER medicine_usage_stock_guard AFTER INSERT OR UPDATE ON public.medicine_usage FOR EACH ROW EXECUTE FUNCTION public.assert_medicine_usage_stock();
DO $$ DECLARE tbl text; BEGIN FOREACH tbl IN ARRAY ARRAY['medicines','medicine_purchases','medicine_usage','vaccines','vaccination_schedules','vaccination_records'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',tbl); END LOOP; END $$;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.medicines,public.medicine_purchases,public.medicine_usage,public.vaccines,public.vaccination_schedules,public.vaccination_records TO authenticated; GRANT SELECT ON public.medicine_stock,public.upcoming_vaccination_reminders,public.medicine_expiry_alerts TO authenticated;
CREATE POLICY medicines_select_members ON public.medicines FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY medicines_write_manager ON public.medicines FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY medicine_purchases_select_members ON public.medicine_purchases FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY medicine_purchases_write_manager ON public.medicine_purchases FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(entered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY medicine_usage_select_members ON public.medicine_usage FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY medicine_usage_write_manager ON public.medicine_usage FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(administered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY vaccines_select_members ON public.vaccines FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY vaccines_write_manager ON public.vaccines FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY vaccination_schedules_select_members ON public.vaccination_schedules FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY vaccination_schedules_write_manager ON public.vaccination_schedules FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(created_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
CREATE POLICY vaccination_records_select_members ON public.vaccination_records FOR SELECT TO authenticated USING(public.is_farm_member(farm_id)); CREATE POLICY vaccination_records_write_manager ON public.vaccination_records FOR ALL TO authenticated USING(public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[])) WITH CHECK(administered_by=auth.uid() AND public.user_has_farm_role(farm_id,ARRAY['OWNER','MANAGER']::public.farm_role[]));
